[project]
name = "gabrielmonti-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-blog-plugin>=0.25",
    "mkdocs-material>=9.7.1",
]
